server:
    port: 9090
    tomcat:
        access_log_enabled: true
        basedir: target/tomcat
spring:
    application:
        name: spring-boot-sample-web-ui
    datasource:
        driverClassName: org.hsqldb.jdbcDriver
        url: jdbc:hsqldb:mem:webuimessages
        username: sa
        password:
    jpa:
        database: HSQL
        show-sql: true
    thymeleaf:
        cache: false
security:
    user:
        password: admin	